# Utiliser une image de base officielle de PHP avec Apache
FROM php:8.1-apache

# Installer les extensions PHP nécessaires
RUN docker-php-ext-install pdo pdo_mysql

# Définir le répertoire de travail dans le conteneur
WORKDIR /var/www/html

# Copier le code de l'application dans le conteneur
COPY . .

# Installer les dépendances Composer si nécessaire
# COPY composer.json composer.lock ./
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN composer install

# Exposer le port sur lequel l'application fonctionnera
EXPOSE 80